// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Index_steup: typeof import('./src/components/Form/index_steup.vue')['default']
    Main: typeof import('./src/components/Form/main/index.vue')['default']
  }
}

export {}
